version: '3'
networks:
  traefiknet:
    external: true

services:
  client:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.client.prod
    networks:
      - traefiknet
    volumes:
      - ./client:/app
      - public-data:/app/public/data
    # ports:
    #   - "80:80"
    #   - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mensapwarouter.entrypoints=web, websecure"
      - "traefik.http.routers.mensapwarouter.rule=Host(`mensa.heylinus.de`)"
      - "traefik.http.routers.mensapwarouter.tls=true" 
      - "traefik.http.routers.mensapwarouter.tls.certresolver=production"

  app:
    restart: unless-stopped
    image: node:18
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm start
    environment:
      - DB_URL=mongodb://db:27017/mydatabase
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: mongo
    volumes:
      - mongo-data:/data/db

  nightly:
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile.nightly
    volumes:
      - public-data:/app/out

volumes:
  mongo-data:
  public-data:
  