# Base image
FROM python:3.8

# Set working directory
WORKDIR /app

# Install Python packages
RUN pip install requests openai Pillow

# Copy files
COPY nightly_task/ ./

# Make the script executable
RUN chmod +x /app/script.py

RUN mkdir -p /app/logs && touch /app/logs/cron.log && chmod 0666 /app/logs/cron.log

# Install cron and set it up
RUN apt-get update && apt-get install -y cron
ADD nightly_task/crontab /etc/cron.d/nightly-task-cron
RUN chmod 0644 /etc/cron.d/nightly-task-cron
RUN crontab /etc/cron.d/nightly-task-cron

# run the script
RUN mkdir -p /app/out
RUN python script.py

CMD cron -f
