# Base image
FROM node:18 as build

# Set working directory
WORKDIR /app

# Install dependencies
COPY client/package*.json ./
RUN npm install

# Build app
COPY client/ ./
RUN npm run build

# Production environment
FROM nginx:alpine

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
