# Base image
FROM python:3.8
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

# Set working directory
WORKDIR /app

# Install Python packages
RUN pip install requests openai Pillow

# Copy files
COPY nightly_task/ ./

# Make the script executable
RUN chmod +x /app/script.py

# Create a log file and make it writable
RUN mkdir -p /app/logs && touch /app/logs/cron.log && chmod 0666 /app/logs/cron.log

# Print the environment variables to a file
RUN env > /root/env_var.sh
# Make the file executable
RUN chmod +x /root/env_var.sh

# Install cron and set it up
RUN apt-get update && apt-get install -y cron
ADD nightly_task/crontab /etc/cron.d/nightly-task-cron
RUN chmod 0644 /etc/cron.d/nightly-task-cron
RUN crontab /etc/cron.d/nightly-task-cron

# run the script
RUN mkdir -p /app/out

# run the script in the background and cron in the foreground
#CMD python script.py & cron -f

# only run the cronjob
CMD cron -f
