name: Deploy to Server

on:
  push:
    branches:
      - production

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Images
      run: |
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        export VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}
        export VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}
        docker-compose -f docker-compose.prod.yml build
        docker-compose -f docker-compose.prod.yml push

    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v4.1.8
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        REMOTE_HOST: ${{ secrets.SERVER_HOST }}
        REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        SCRIPT_AFTER: |
          cd ~/MensaPWA
          git fetch origin production
          git reset --hard origin/production
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          export VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}
          export VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}
          cd client
          npm install
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          npx semantic-release
          cd ..
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up --build -d --remove-orphans
